### ISSUE TITLE
UI doesn't reflect saved value

### ISSUE THREAD

**Issue by Marco-Daniel** [marcbelletre/acf-rrule#15]
Hello,

When setting the frequency to montly you have the option of setting it on a monthday or weekday basis. 
When selecting weekdays the checkmarks with wich week of that month the selected day(s) applies to doesn't save, or at least doesn't show the saved value.

Hope that makes any sense, if not i'll gladly elaborate

**Comment by Marco-Daniel** [comment]
Did you already have a change to look into this? It's quite annoying since the fields are required, so when wanting to change something you always have to reapply the settings (and remeber what the settings were).

**Comment by marcbelletre** [comment]
Hi Marco-Daniel,

Sorry I've been very busy for a while. I'll take a look at this later today or tomorrow. Thanks for your patience!

**Comment by Marco-Daniel** [comment]
Hi marcbelletre,

Great, if you need any more info please let me know.

**Comment by marcbelletre** [comment]
Hi @Marco-Daniel,

The bug has been fixed. The values were actually being saved and it was only a display issue.

Sorry again for the delay. Cheers!

**Comment by Marco-Daniel** [comment]
Thanks @marcbelletre! Can confirm that's it's fixed now.
