### ISSUE TITLE
end type: count, no end date?

### ISSUE THREAD

**Issue by Marco-Daniel** [marcbelletre/acf-rrule#16]
Hello,

Not sure if it's a bug or not. But when the end_type is set to count, there is no end_date generated?

**Comment by marcbelletre** [comment]
Hi @Marco-Daniel,

It wasn't really a bug as the recurr library does not provide any method for retrieving the end date of a recurrence when using `setCount`. I was still able to make a little change and set the last occurrence of the collection as the end date.  

I just released v1.2.3 with a fix for this one and #15.

**Comment by Marco-Daniel** [comment]
Thanks @marcbelletre!
