### ISSUE TITLE
Selected Month Days aren't reflected in the calendar

### ISSUE THREAD

**Issue by Virusmater** [marcbelletre/acf-rrule#19]
Similar for https://github.com/marcbelletre/acf-rrule/issues/15, but affects only Month Days selection:
![image](https://user-images.githubusercontent.com/99446/206262040-cefcfd88-2ac6-45f9-a81f-2e09ef6f0538.png)

I am on a latest version

Great plugin, 
Thx!

**Comment by marcbelletre** [comment]
Hi @Virusmater,

Thank your for reporting this. 
The current value actually displays the value which is saved in the database but I agree that it would make more sense to update it based on the current selection.  

For now the plugin only uses a PHP library. The text representation of the RRule string is retrieved when the field's value is loaded server-side. To make it reactive we would have to import a client-side library such as [rrule.js](https://github.com/jakubroztocil/rrule) which would make the plugin heavier. I'm not sure if it's worth it. What do you think?

**Comment by Virusmater** [comment]
Hey there,
Maybe I wasn't clear. I don't have any issues with the text representation of the rule. 
The problem that 17th and 19th dates aren't marked as selected in the calendar.
Hope with an example its gonna be easier to understand me
Actual:
![image](https://user-images.githubusercontent.com/99446/210433546-2ae550c2-1b0c-4443-9903-165e66a7ba4b.png)
Expected:
![image](https://user-images.githubusercontent.com/99446/210433613-1eda3943-e641-413c-850a-3290ed332e50.png)

**Comment by perrelet** [comment]
Ahoy,

#1 @marcbelletre thank you for this repo. I had one of those classic moments yesterday of building a field group out that calcs rrules to find that at the end of the workday someone had already done it better than me 🤣 Bravo!

#2 I immediately ran into the same issue described by @Virusmater. The issue appears to be the result of setting the `$strict` flag to `true` when calling `in_array` in `class-acf-field-rrule.php` on line `362`. ie:

```php
$selected = is_array($field['value']) && in_array($day, $field['value']['monthdays'], true);
```

Should be:

```php
$selected = is_array($field['value']) && in_array($day, $field['value']['monthdays']);
```

Was there a reason for setting `$strict = true`?

🚀

**Comment by marcbelletre** [comment]
Hello there!

I would like to apologize for leaving this issue open for so long. I've been busy and totally forgot about it.  
Thank you @perrelet for finding the cause of the bug. It was indeed introduced by PR #12. I have actually no idea why the strict comparison was set up here.

Anyway this has been fixed and will be published in the next release. 

Cheers!
