### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by LucasDemea** [marcbelletre/acf-rrule#2]
Hi,
There's a small bug in the "Start time" french translation. It should be translated "Heure de début".

**Comment by marcbelletre** [comment]
Hi,

I can't see any translation error on my side. Start Time is already translated to "Heure de début". What do you see exactly? Could you provide a screen capture?

<img width="557" alt="Capture d’écran 2020-11-18 à 10 44 46" src="https://user-images.githubusercontent.com/6853334/99513838-5b118580-298b-11eb-94b2-4741d5ea5143.png">
