### ISSUE TITLE
Repeat events on front end

### ISSUE THREAD

**Issue by Jay-miche** [marcbelletre/acf-rrule#24]
I have a recurring event every wednesday at 7. However, on the front end of the site it's only showing one night. Is there something I should do?

**Comment by marcbelletre** [comment]
Hi @Jay-miche,

Could you please provide more context regarding your issue? Without seeing the code you're using on the front-end I won't be able to help.

**Comment by Jay-miche** [comment]
Hello! I'm sorry I missed this message. I will send a screenshot soon.

**Comment by marcbelletre** [comment]
Hi,  

I'm afraid a screenshot won't help. The code you're using on the front-end would. 

This plugin provides the field for generating the RRULE string and the collection of dates but the front-end implementation is totally up to you. If you need to display the dates you just have to use `get_field()` which will retrieve an array that is described [here](https://github.com/marcbelletre/acf-rrule?tab=readme-ov-file#usage).

**Comment by Jay-miche** [comment]
I think that's where the breakdown is. I did not create this website with
code, I just used some templates. However, we did have a company to provide
this website and they used some code. I found this plug-in to avoid their
$300 charge to have recurring events on the website. For example, we have
an event every Friday of the month. As of now, I have to upload each event
one by one to have the correct flyer and date. So there should be 4 events,
the same flyer and description but different dates.

I downloaded the plugin and I did not see the different dates on the front
end of the site. How do I see every event on the front end with different
dates?

**Comment by marcbelletre** [comment]
As I said earlier this plugin only provides a field for the back-end. It is made for developers. You can't expect it to work magically right after installing it.

If you don't know how to write code you will need to hire a developer or an agency that will do it for you.

Otherwise you can try some other plugin like WP Event Manager that are made for non-developers.
