### ISSUE TITLE
Field not showing after 1.4 update

### ISSUE THREAD

**Issue by ybailly04** [marcbelletre/acf-rrule#25]
Hello,
After the 1.4 update, the field doesn't appear anymore in the back office when i'm writing a post. The label is the only thing visible on the field.
Wordpress version is 6.4.2 and ACF version is 6.2.4. I use a custom theme with Timber 2 as a framework.

It worked wonderfully last week when i used it in my website, but since i made the update it won't work. I tried changing the ID but it didn't solve the issue. Any idea why it's not working ?

Thanks again for your work on this plugin.

**Comment by ybailly04** [comment]
Found the issue !
It seems the `include` repository is not uptaded from 1.3 to 1.4, so the `render.php` file is missing from the plugin files !

**Comment by marcbelletre** [comment]
Hi @ybailly04,

I forgot to add the `include`directory to the Wordpress SVN repository. I just force-pushed it to the 1.4.0 tag so you can remove the plugin and download it again, that should work again.  

I'm really sorry for the inconvenience! Please tell me if everything works fine after re-downloading.

**Comment by ybailly04** [comment]
Works perfectly after re-downloading, thank you!
