### ISSUE TITLE
Javscript Error when attaching to a Gutenberg Custom Post Type

### ISSUE THREAD

**Issue by strada-jeff** [marcbelletre/acf-rrule#27]
I registered a Custom Post Type using Advanced Custom Fields, created a new field group that contained an ACF RRule field, and ended up with a Javascript Error. 

![Screenshot 2024-02-09 at 1 23 42 PM](https://github.com/marcbelletre/acf-rrule/assets/75342563/46b18116-f3b6-41dc-a9aa-c0693a576fbd)

This seems to happen only when the I've got the rule attached to the Gutenberg editor. If I switch to the classic editors the javascript error isn't present.

I tried to wrap the following:

```
acf.add_action('ready_field/type=rrule', initialize_field);
acf.add_action('append_field/type=rrule', initialize_field);
```

with:

```
jQuery( document ).ready( function( $ ) {
    if ( typeof acf !== 'undefined' ) {
        console.log( 'ACF is defined', acf );
    }
});
```

as outlined in the [ACF Javascript API doc ](https://www.advancedcustomfields.com/resources/javascript-api/) and that seems to get rid of the JS error, but the 'end rules' don't seem to be initializing.

![Screenshot 2024-02-09 at 1 44 05 PM](https://github.com/marcbelletre/acf-rrule/assets/75342563/0ba8c735-b39a-4a3c-bb14-78bc588cdd08)

I'm not that great with jQuery so I hope this helps to describe the issue. Let me know if I can clarify.

**Comment by marcbelletre** [comment]
Hi @strada-jeff,

Thank you for the bug report. I got the same error this morning. Not sure why this happened but removing the `trigger` fixed the issue. Maybe jQuery was updated in the latest Wordpress version.

Anyway you can update ACF RRule to 1.4.2 :)

**Comment by strada-jeff** [comment]
@marcbelletre That worked great. Thanks. Cheers.
