### ISSUE TITLE
Additional Validation Needed

### ISSUE THREAD

**Issue by SpeedyTechie** [marcbelletre/acf-rrule#4]
Thanks so much for your work on this plugin, it's very handy!

I ran into one issue. If you enter an end date that is before the start date, or an end date that results in there being no occurrences (e.g. the recurrence is weekly on Wednesday, but there are no Wednesdays between the start and end date), PHP throws an error.

Adding validation for these cases would be great, in case a user enters something invalid.

Thanks again!

**Comment by marcbelletre** [comment]
Hi Zane,

Thank you for your support!

I couldn't reproduce the PHP error you were talking about. I created a recurrence from March 11 to March 4 and PHP did not thrown any error. If I try to display the field's content in a template I just get an empty array but still no error. Could you please provide more information or maybe a screenshot?

That being said it would still be a great idea to add validation for this. I'm working on it 😉

**Comment by SpeedyTechie** [comment]
So I just tested it out again, and I'm no longer getting the error. I think it may have been due to some PHP I had written to process the input. My bad!

Anyway, like you said, adding validation is probably still a good idea, haha. Thanks!

**Comment by marcbelletre** [comment]
I released a new version. The plugin now handles errors for the following cases:

- The start date is empty
- The recurrence is configured to end at a specific date but the end date is empty
- The start date is after the end date
- The frequency interval is lower than 1

The plugin is also up-to-date on the [Wordpress plugin repository](https://wordpress.org/plugins/acf-rrule-field/).
Feel free to reopen if you find any issue with these changes.

Thanks again 🙂
