### ISSUE TITLE
On save error

### ISSUE THREAD

**Issue by ellemaker** [marcbelletre/acf-rrule#9]
Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone

/wp-content/plugins/acf-rrule-field/vendor/simshaun/recurr/src/Recurr/Rule.php on line 804

**Comment by marcbelletre** [comment]
Hi,

Could you please provide more context?

**Comment by Marco-Daniel** [comment]
I'm running into the same error. 

It only happens when setting the end date to: "At a specific date". If the end date is: "After a number of occurencess" or set to "Never" everything works fine.

The end date is set in the future in regards to the starting date.

**Comment by marcbelletre** [comment]
Hi @Marco-Daniel,

Thank you for reporting. I still can't reproduce the error using the specific date option. Could you please tell me what timezone is set in your Wordpress settings?

**Comment by marcbelletre** [comment]
I finally figured out what the problem was. The error occurred when the `timezone_string` option was missing. It is now set as UTC by default.
The new release is already available on the Wordpress plugins directory.

**Comment by Marco-Daniel** [comment]
@marcbelletre Just tested the update and can comfirm it's fixed, thank you!
